name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release --verbose
      - name: Test
        run: cargo test --verbose
      - name: Build examples
        run: cargo build --examples --release --verbose
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: mighty-wasm-dec-${{ matrix.os }}
          path: |
            target/release/mighty-wasm-dec
            target/release/mighty-wasm-dec.exe
